# Generated by Django 5.1.2 on 2024-10-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0003_location_star_alter_reviews_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
