# Generated by Django 5.1.2 on 2024-10-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0004_alter_location_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
