# Generated by Django 5.1.2 on 2024-10-20 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_remove_profile_phone_number_and_more'),
        ('Destinations', '0006_bookings_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.profile'),
        ),
    ]
