# Generated by Django 5.1.2 on 2024-10-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0009_badges_bookings_date_location_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('1', 'Credit'), ('0', 'Debit'), ('2', 'Donation')], max_length=10),
        ),
    ]
