# Generated by Django 5.1.2 on 2024-10-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0010_transaction_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
