# Generated by Django 5.1.2 on 2024-10-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0011_alter_bookings_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together=set(),
        ),
    ]
